// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: stats/stats.proto

package stats

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StatsService_GetPostStats_FullMethodName            = "/stats.StatsService/GetPostStats"
	StatsService_GetPostViewsTimeline_FullMethodName    = "/stats.StatsService/GetPostViewsTimeline"
	StatsService_GetPostLikesTimeline_FullMethodName    = "/stats.StatsService/GetPostLikesTimeline"
	StatsService_GetPostCommentsTimeline_FullMethodName = "/stats.StatsService/GetPostCommentsTimeline"
	StatsService_GetTopPosts_FullMethodName             = "/stats.StatsService/GetTopPosts"
	StatsService_GetTopUsers_FullMethodName             = "/stats.StatsService/GetTopUsers"
)

// StatsServiceClient is the client API for StatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatsServiceClient interface {
	GetPostStats(ctx context.Context, in *PostStatsRequest, opts ...grpc.CallOption) (*PostStatsResponse, error)
	GetPostViewsTimeline(ctx context.Context, in *PostTimelineRequest, opts ...grpc.CallOption) (*TimelineResponse, error)
	GetPostLikesTimeline(ctx context.Context, in *PostTimelineRequest, opts ...grpc.CallOption) (*TimelineResponse, error)
	GetPostCommentsTimeline(ctx context.Context, in *PostTimelineRequest, opts ...grpc.CallOption) (*TimelineResponse, error)
	GetTopPosts(ctx context.Context, in *TopRequest, opts ...grpc.CallOption) (*TopPostsResponse, error)
	GetTopUsers(ctx context.Context, in *TopRequest, opts ...grpc.CallOption) (*TopUsersResponse, error)
}

type statsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatsServiceClient(cc grpc.ClientConnInterface) StatsServiceClient {
	return &statsServiceClient{cc}
}

func (c *statsServiceClient) GetPostStats(ctx context.Context, in *PostStatsRequest, opts ...grpc.CallOption) (*PostStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostStatsResponse)
	err := c.cc.Invoke(ctx, StatsService_GetPostStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetPostViewsTimeline(ctx context.Context, in *PostTimelineRequest, opts ...grpc.CallOption) (*TimelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimelineResponse)
	err := c.cc.Invoke(ctx, StatsService_GetPostViewsTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetPostLikesTimeline(ctx context.Context, in *PostTimelineRequest, opts ...grpc.CallOption) (*TimelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimelineResponse)
	err := c.cc.Invoke(ctx, StatsService_GetPostLikesTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetPostCommentsTimeline(ctx context.Context, in *PostTimelineRequest, opts ...grpc.CallOption) (*TimelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimelineResponse)
	err := c.cc.Invoke(ctx, StatsService_GetPostCommentsTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetTopPosts(ctx context.Context, in *TopRequest, opts ...grpc.CallOption) (*TopPostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopPostsResponse)
	err := c.cc.Invoke(ctx, StatsService_GetTopPosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetTopUsers(ctx context.Context, in *TopRequest, opts ...grpc.CallOption) (*TopUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopUsersResponse)
	err := c.cc.Invoke(ctx, StatsService_GetTopUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatsServiceServer is the server API for StatsService service.
// All implementations must embed UnimplementedStatsServiceServer
// for forward compatibility.
type StatsServiceServer interface {
	GetPostStats(context.Context, *PostStatsRequest) (*PostStatsResponse, error)
	GetPostViewsTimeline(context.Context, *PostTimelineRequest) (*TimelineResponse, error)
	GetPostLikesTimeline(context.Context, *PostTimelineRequest) (*TimelineResponse, error)
	GetPostCommentsTimeline(context.Context, *PostTimelineRequest) (*TimelineResponse, error)
	GetTopPosts(context.Context, *TopRequest) (*TopPostsResponse, error)
	GetTopUsers(context.Context, *TopRequest) (*TopUsersResponse, error)
	mustEmbedUnimplementedStatsServiceServer()
}

// UnimplementedStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatsServiceServer struct{}

func (UnimplementedStatsServiceServer) GetPostStats(context.Context, *PostStatsRequest) (*PostStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostStats not implemented")
}
func (UnimplementedStatsServiceServer) GetPostViewsTimeline(context.Context, *PostTimelineRequest) (*TimelineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostViewsTimeline not implemented")
}
func (UnimplementedStatsServiceServer) GetPostLikesTimeline(context.Context, *PostTimelineRequest) (*TimelineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostLikesTimeline not implemented")
}
func (UnimplementedStatsServiceServer) GetPostCommentsTimeline(context.Context, *PostTimelineRequest) (*TimelineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostCommentsTimeline not implemented")
}
func (UnimplementedStatsServiceServer) GetTopPosts(context.Context, *TopRequest) (*TopPostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopPosts not implemented")
}
func (UnimplementedStatsServiceServer) GetTopUsers(context.Context, *TopRequest) (*TopUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopUsers not implemented")
}
func (UnimplementedStatsServiceServer) mustEmbedUnimplementedStatsServiceServer() {}
func (UnimplementedStatsServiceServer) testEmbeddedByValue()                      {}

// UnsafeStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatsServiceServer will
// result in compilation errors.
type UnsafeStatsServiceServer interface {
	mustEmbedUnimplementedStatsServiceServer()
}

func RegisterStatsServiceServer(s grpc.ServiceRegistrar, srv StatsServiceServer) {
	// If the following call pancis, it indicates UnimplementedStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StatsService_ServiceDesc, srv)
}

func _StatsService_GetPostStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetPostStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetPostStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetPostStats(ctx, req.(*PostStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetPostViewsTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetPostViewsTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetPostViewsTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetPostViewsTimeline(ctx, req.(*PostTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetPostLikesTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetPostLikesTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetPostLikesTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetPostLikesTimeline(ctx, req.(*PostTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetPostCommentsTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetPostCommentsTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetPostCommentsTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetPostCommentsTimeline(ctx, req.(*PostTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetTopPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetTopPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetTopPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetTopPosts(ctx, req.(*TopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetTopUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetTopUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetTopUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetTopUsers(ctx, req.(*TopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatsService_ServiceDesc is the grpc.ServiceDesc for StatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stats.StatsService",
	HandlerType: (*StatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPostStats",
			Handler:    _StatsService_GetPostStats_Handler,
		},
		{
			MethodName: "GetPostViewsTimeline",
			Handler:    _StatsService_GetPostViewsTimeline_Handler,
		},
		{
			MethodName: "GetPostLikesTimeline",
			Handler:    _StatsService_GetPostLikesTimeline_Handler,
		},
		{
			MethodName: "GetPostCommentsTimeline",
			Handler:    _StatsService_GetPostCommentsTimeline_Handler,
		},
		{
			MethodName: "GetTopPosts",
			Handler:    _StatsService_GetTopPosts_Handler,
		},
		{
			MethodName: "GetTopUsers",
			Handler:    _StatsService_GetTopUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats/stats.proto",
}
