// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: stats/stats.proto

package stats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricType int32

const (
	MetricType_VIEWS    MetricType = 0
	MetricType_LIKES    MetricType = 1
	MetricType_COMMENTS MetricType = 2
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0: "VIEWS",
		1: "LIKES",
		2: "COMMENTS",
	}
	MetricType_value = map[string]int32{
		"VIEWS":    0,
		"LIKES":    1,
		"COMMENTS": 2,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_stats_stats_proto_enumTypes[0].Descriptor()
}

func (MetricType) Type() protoreflect.EnumType {
	return &file_stats_stats_proto_enumTypes[0]
}

func (x MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricType.Descriptor instead.
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{0}
}

type PostStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostStatsRequest) Reset() {
	*x = PostStatsRequest{}
	mi := &file_stats_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostStatsRequest) ProtoMessage() {}

func (x *PostStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostStatsRequest.ProtoReflect.Descriptor instead.
func (*PostStatsRequest) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{0}
}

func (x *PostStatsRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type PostStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	ViewsCount    uint64                 `protobuf:"varint,2,opt,name=views_count,json=viewsCount,proto3" json:"views_count,omitempty"`
	LikesCount    uint64                 `protobuf:"varint,3,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`
	CommentsCount uint64                 `protobuf:"varint,4,opt,name=comments_count,json=commentsCount,proto3" json:"comments_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostStatsResponse) Reset() {
	*x = PostStatsResponse{}
	mi := &file_stats_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostStatsResponse) ProtoMessage() {}

func (x *PostStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostStatsResponse.ProtoReflect.Descriptor instead.
func (*PostStatsResponse) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{1}
}

func (x *PostStatsResponse) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PostStatsResponse) GetViewsCount() uint64 {
	if x != nil {
		return x.ViewsCount
	}
	return 0
}

func (x *PostStatsResponse) GetLikesCount() uint64 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

func (x *PostStatsResponse) GetCommentsCount() uint64 {
	if x != nil {
		return x.CommentsCount
	}
	return 0
}

type PostTimelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Days          uint32                 `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostTimelineRequest) Reset() {
	*x = PostTimelineRequest{}
	mi := &file_stats_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostTimelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTimelineRequest) ProtoMessage() {}

func (x *PostTimelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTimelineRequest.ProtoReflect.Descriptor instead.
func (*PostTimelineRequest) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{2}
}

func (x *PostTimelineRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PostTimelineRequest) GetDays() uint32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type TimelineItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineItem) Reset() {
	*x = TimelineItem{}
	mi := &file_stats_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineItem) ProtoMessage() {}

func (x *TimelineItem) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineItem.ProtoReflect.Descriptor instead.
func (*TimelineItem) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{3}
}

func (x *TimelineItem) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *TimelineItem) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TimelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TimelineItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineResponse) Reset() {
	*x = TimelineResponse{}
	mi := &file_stats_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineResponse) ProtoMessage() {}

func (x *TimelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineResponse.ProtoReflect.Descriptor instead.
func (*TimelineResponse) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{4}
}

func (x *TimelineResponse) GetItems() []*TimelineItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type TopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricType    MetricType             `protobuf:"varint,1,opt,name=metric_type,json=metricType,proto3,enum=stats.MetricType" json:"metric_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopRequest) Reset() {
	*x = TopRequest{}
	mi := &file_stats_stats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopRequest) ProtoMessage() {}

func (x *TopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopRequest.ProtoReflect.Descriptor instead.
func (*TopRequest) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{5}
}

func (x *TopRequest) GetMetricType() MetricType {
	if x != nil {
		return x.MetricType
	}
	return MetricType_VIEWS
}

type TopPostItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopPostItem) Reset() {
	*x = TopPostItem{}
	mi := &file_stats_stats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopPostItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopPostItem) ProtoMessage() {}

func (x *TopPostItem) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopPostItem.ProtoReflect.Descriptor instead.
func (*TopPostItem) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{6}
}

func (x *TopPostItem) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *TopPostItem) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TopPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*TopPostItem         `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopPostsResponse) Reset() {
	*x = TopPostsResponse{}
	mi := &file_stats_stats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopPostsResponse) ProtoMessage() {}

func (x *TopPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopPostsResponse.ProtoReflect.Descriptor instead.
func (*TopPostsResponse) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{7}
}

func (x *TopPostsResponse) GetPosts() []*TopPostItem {
	if x != nil {
		return x.Posts
	}
	return nil
}

type TopUserItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopUserItem) Reset() {
	*x = TopUserItem{}
	mi := &file_stats_stats_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUserItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUserItem) ProtoMessage() {}

func (x *TopUserItem) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUserItem.ProtoReflect.Descriptor instead.
func (*TopUserItem) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{8}
}

func (x *TopUserItem) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TopUserItem) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TopUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*TopUserItem         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopUsersResponse) Reset() {
	*x = TopUsersResponse{}
	mi := &file_stats_stats_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUsersResponse) ProtoMessage() {}

func (x *TopUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUsersResponse.ProtoReflect.Descriptor instead.
func (*TopUsersResponse) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{9}
}

func (x *TopUsersResponse) GetUsers() []*TopUserItem {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_stats_stats_proto protoreflect.FileDescriptor

const file_stats_stats_proto_rawDesc = "" +
	"\n" +
	"\x11stats/stats.proto\x12\x05stats\x1a\x1fgoogle/protobuf/timestamp.proto\"+\n" +
	"\x10PostStatsRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x04R\x06postId\"\x95\x01\n" +
	"\x11PostStatsResponse\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x04R\x06postId\x12\x1f\n" +
	"\vviews_count\x18\x02 \x01(\x04R\n" +
	"viewsCount\x12\x1f\n" +
	"\vlikes_count\x18\x03 \x01(\x04R\n" +
	"likesCount\x12%\n" +
	"\x0ecomments_count\x18\x04 \x01(\x04R\rcommentsCount\"B\n" +
	"\x13PostTimelineRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x04R\x06postId\x12\x12\n" +
	"\x04days\x18\x02 \x01(\rR\x04days\"T\n" +
	"\fTimelineItem\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\"=\n" +
	"\x10TimelineResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.stats.TimelineItemR\x05items\"@\n" +
	"\n" +
	"TopRequest\x122\n" +
	"\vmetric_type\x18\x01 \x01(\x0e2\x11.stats.MetricTypeR\n" +
	"metricType\"<\n" +
	"\vTopPostItem\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x04R\x06postId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\"<\n" +
	"\x10TopPostsResponse\x12(\n" +
	"\x05posts\x18\x01 \x03(\v2\x12.stats.TopPostItemR\x05posts\"<\n" +
	"\vTopUserItem\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\"<\n" +
	"\x10TopUsersResponse\x12(\n" +
	"\x05users\x18\x01 \x03(\v2\x12.stats.TopUserItemR\x05users*0\n" +
	"\n" +
	"MetricType\x12\t\n" +
	"\x05VIEWS\x10\x00\x12\t\n" +
	"\x05LIKES\x10\x01\x12\f\n" +
	"\bCOMMENTS\x10\x022\xb1\x03\n" +
	"\fStatsService\x12A\n" +
	"\fGetPostStats\x12\x17.stats.PostStatsRequest\x1a\x18.stats.PostStatsResponse\x12K\n" +
	"\x14GetPostViewsTimeline\x12\x1a.stats.PostTimelineRequest\x1a\x17.stats.TimelineResponse\x12K\n" +
	"\x14GetPostLikesTimeline\x12\x1a.stats.PostTimelineRequest\x1a\x17.stats.TimelineResponse\x12N\n" +
	"\x17GetPostCommentsTimeline\x12\x1a.stats.PostTimelineRequest\x1a\x17.stats.TimelineResponse\x129\n" +
	"\vGetTopPosts\x12\x11.stats.TopRequest\x1a\x17.stats.TopPostsResponse\x129\n" +
	"\vGetTopUsers\x12\x11.stats.TopRequest\x1a\x17.stats.TopUsersResponseB#Z!social-network/common/proto/statsb\x06proto3"

var (
	file_stats_stats_proto_rawDescOnce sync.Once
	file_stats_stats_proto_rawDescData []byte
)

func file_stats_stats_proto_rawDescGZIP() []byte {
	file_stats_stats_proto_rawDescOnce.Do(func() {
		file_stats_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stats_stats_proto_rawDesc), len(file_stats_stats_proto_rawDesc)))
	})
	return file_stats_stats_proto_rawDescData
}

var file_stats_stats_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stats_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_stats_stats_proto_goTypes = []any{
	(MetricType)(0),               // 0: stats.MetricType
	(*PostStatsRequest)(nil),      // 1: stats.PostStatsRequest
	(*PostStatsResponse)(nil),     // 2: stats.PostStatsResponse
	(*PostTimelineRequest)(nil),   // 3: stats.PostTimelineRequest
	(*TimelineItem)(nil),          // 4: stats.TimelineItem
	(*TimelineResponse)(nil),      // 5: stats.TimelineResponse
	(*TopRequest)(nil),            // 6: stats.TopRequest
	(*TopPostItem)(nil),           // 7: stats.TopPostItem
	(*TopPostsResponse)(nil),      // 8: stats.TopPostsResponse
	(*TopUserItem)(nil),           // 9: stats.TopUserItem
	(*TopUsersResponse)(nil),      // 10: stats.TopUsersResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_stats_stats_proto_depIdxs = []int32{
	11, // 0: stats.TimelineItem.date:type_name -> google.protobuf.Timestamp
	4,  // 1: stats.TimelineResponse.items:type_name -> stats.TimelineItem
	0,  // 2: stats.TopRequest.metric_type:type_name -> stats.MetricType
	7,  // 3: stats.TopPostsResponse.posts:type_name -> stats.TopPostItem
	9,  // 4: stats.TopUsersResponse.users:type_name -> stats.TopUserItem
	1,  // 5: stats.StatsService.GetPostStats:input_type -> stats.PostStatsRequest
	3,  // 6: stats.StatsService.GetPostViewsTimeline:input_type -> stats.PostTimelineRequest
	3,  // 7: stats.StatsService.GetPostLikesTimeline:input_type -> stats.PostTimelineRequest
	3,  // 8: stats.StatsService.GetPostCommentsTimeline:input_type -> stats.PostTimelineRequest
	6,  // 9: stats.StatsService.GetTopPosts:input_type -> stats.TopRequest
	6,  // 10: stats.StatsService.GetTopUsers:input_type -> stats.TopRequest
	2,  // 11: stats.StatsService.GetPostStats:output_type -> stats.PostStatsResponse
	5,  // 12: stats.StatsService.GetPostViewsTimeline:output_type -> stats.TimelineResponse
	5,  // 13: stats.StatsService.GetPostLikesTimeline:output_type -> stats.TimelineResponse
	5,  // 14: stats.StatsService.GetPostCommentsTimeline:output_type -> stats.TimelineResponse
	8,  // 15: stats.StatsService.GetTopPosts:output_type -> stats.TopPostsResponse
	10, // 16: stats.StatsService.GetTopUsers:output_type -> stats.TopUsersResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_stats_stats_proto_init() }
func file_stats_stats_proto_init() {
	if File_stats_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stats_stats_proto_rawDesc), len(file_stats_stats_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stats_stats_proto_goTypes,
		DependencyIndexes: file_stats_stats_proto_depIdxs,
		EnumInfos:         file_stats_stats_proto_enumTypes,
		MessageInfos:      file_stats_stats_proto_msgTypes,
	}.Build()
	File_stats_stats_proto = out.File
	file_stats_stats_proto_goTypes = nil
	file_stats_stats_proto_depIdxs = nil
}
