services:
  api-service:
    build:
      context: .
      dockerfile: ./api-service/DockerFile
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - post-service
      - user-service

  user-service:
    build:
      context: .
      dockerfile: ./user-service/DockerFile
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=user-db
      - DB_PORT=5432
      - DB_USER=mydbuser
      - DB_PASSWORD=password
      - DB_NAME=userdb
      - COOKIE_SECRET=my_secret_string
      - KAFKA_BROKERS=kafka:29092
      - KAFKA_USER_TOPIC=user_registrations
      - KAFKA_VIEW_TOPIC=post_views
      - KAFKA_LIKE_TOPIC=post_likes
      - KAFKA_COMMENT_TOPIC=post_comments
    networks:
      - app-network
    depends_on:
      - user-db
      - kafka

  post-service:
    build:
      context: .
      dockerfile: ./post-service/DockerFile
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=post-db
      - DB_PORT=5432
      - DB_USER=mydbuser
      - DB_PASSWORD=password
      - DB_NAME=postdb
      - KAFKA_BROKERS=kafka:29092
      - KAFKA_USER_TOPIC=user_registrations
      - KAFKA_VIEW_TOPIC=post_views
      - KAFKA_LIKE_TOPIC=post_likes
      - KAFKA_COMMENT_TOPIC=post_comments
    networks:
      - app-network
    depends_on:
      - post-db
      - kafka

  user-db:
    image: postgres:14
    environment:
      - POSTGRES_USER=mydbuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=userdb
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  post-db:
    image: postgres:14
    environment:
      - POSTGRES_USER=mydbuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postdb
    volumes:
      - post_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - app-network
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
    networks:
      - app-network

networks:
  app-network:

volumes:
  user_postgres_data:
  post_postgres_data:
  kafka_data:
