services:
  api-service:
    build:
      context: .
      dockerfile: ./api-service/DockerFile
    ports:
      - "8080:8080"
    networks:
      - app-network

  user-service:
    build:
      context: .
      dockerfile: ./user-service/DockerFile
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=user-db
      - DB_PORT=5432
      - DB_USER=mydbuser
      - DB_PASSWORD=password
      - DB_NAME=userdb
      - COOKIE_SECRET=my_secret_string
    networks:
      - app-network
    depends_on:
      - user-db

  post-service:
    build:
      context: .
      dockerfile: ./post-service/DockerFile
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=post-db
      - DB_PORT=5432
      - DB_USER=mydbuser
      - DB_PASSWORD=password
      - DB_NAME=postdb
    networks:
      - app-network
    depends_on:
      - post-db

  user-db:
    image: postgres:14
    environment:
      - POSTGRES_USER=mydbuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=userdb
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  post-db:
    image: postgres:14
    environment:
      - POSTGRES_USER=mydbuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postdb
    volumes:
      - post_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network

networks:
  app-network:

volumes:
  user_postgres_data:
  post_postgres_data:
