FROM golang:1.23.5

WORKDIR /app

COPY go.mod ./
COPY ./api-service ./api-service
COPY ./common ./common
COPY ./docs ./docs

RUN go mod tidy
RUN go mod download

RUN go build -o api-service ./api-service

CMD ["./api-service/api-service"]